In [1]:
import numpy as np 
from main import LogisticRegression 

In [2]:
X = np.load("data/design_matrix_credit.npy")
y = np.load("data/targets_credit.npy")
# print(X)
# exit()
a = LogisticRegression(learning_rate=1e-6)
X_train, X_test, y_train, y_test = a.preprocessing(X, y)
a.fit(X_train, y_train)
print(a.accuracy_score(X_train, y_train))
print(a.accuracy_score(X_test, y_test))
print(np.mean(y), np.mean(y_train), np.mean(y_test))


0.8091044776119403
0.8123232323232323
0.2212 0.22119402985074627 0.22121212121212122


In [54]:
print(np.load("data/design_matrix_credit.npy"))

[[1.0000e+00 0.0000e+00 1.0000e+00 ... 2.2301e+04 0.0000e+00 3.6400e+03]
 [1.0000e+00 0.0000e+00 1.0000e+00 ... 6.3200e+02 3.1600e+02 0.0000e+00]
 [1.0000e+00 0.0000e+00 1.0000e+00 ... 3.0430e+04 2.5700e+02 0.0000e+00]
 ...
 [1.0000e+00 1.0000e+00 0.0000e+00 ... 0.0000e+00 3.5200e+03 0.0000e+00]
 [1.0000e+00 1.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.0000e+00 1.0000e+00 0.0000e+00 ... 7.0000e+03 0.0000e+00 4.0000e+03]]
